spring.application.name=finance

spring.data.mongodb.uri=mongodb+srv://mjolnir5690_db_user:FinancialStrongPassword123@finance.bk1jzcy.mongodb.net/finance_db?retryWrites=true&w=majority

spring.data.mongodb.auto-index-creation=true

jwt.secret=getmysecretkeyyooitmysecretkeyooit
jwt.expiration=86400000